#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafetyExam
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SafetyExam")]
	public partial class SafetyExamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public SafetyExamDataContext() : 
				base(global::SafetyExam.Properties.Settings.Default.SafetyExamConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SafetyExamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SafetyExamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SafetyExamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SafetyExamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DANXUAN> DANXUANs
		{
			get
			{
				return this.GetTable<DANXUAN>();
			}
		}

        [Function(Name = "NEWID", IsComposable = true)]
        public Guid NEWID()
        {
            return ((Guid)(this.ExecuteMethodCall(this,
           ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
        }

	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANXUAN")]
	public partial class DANXUAN
	{
		
		private string _Content;
		
		private string _A;
		
		private string _Answer;
		
		private string _ClassName;
		
		private System.Nullable<double> _TestLevel;
		
		private System.Nullable<double> _ClassDes2;
		
		private string _ClassDes3;
		
		private string _ClassDes4;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private string _ClassDes1;
		
		private System.Nullable<int> _ID;
		
		public DANXUAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(255)")]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="NVarChar(255)")]
		public string A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(255)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(255)")]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this._ClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestLevel", DbType="Float")]
		public System.Nullable<double> TestLevel
		{
			get
			{
				return this._TestLevel;
			}
			set
			{
				if ((this._TestLevel != value))
				{
					this._TestLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDes2", DbType="Float")]
		public System.Nullable<double> ClassDes2
		{
			get
			{
				return this._ClassDes2;
			}
			set
			{
				if ((this._ClassDes2 != value))
				{
					this._ClassDes2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDes3", DbType="NVarChar(255)")]
		public string ClassDes3
		{
			get
			{
				return this._ClassDes3;
			}
			set
			{
				if ((this._ClassDes3 != value))
				{
					this._ClassDes3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDes4", DbType="NVarChar(255)")]
		public string ClassDes4
		{
			get
			{
				return this._ClassDes4;
			}
			set
			{
				if ((this._ClassDes4 != value))
				{
					this._ClassDes4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(255)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this._B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(255)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(255)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDes1", DbType="NVarChar(255)")]
		public string ClassDes1
		{
			get
			{
				return this._ClassDes1;
			}
			set
			{
				if ((this._ClassDes1 != value))
				{
					this._ClassDes1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
